name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0
      - name: Run Renovate
        uses: renovatebot/github-action@v42.0.4
        with:
          token: ${{ steps.app-token.outputs.token }}
          configurationFile: renovate.json
        env:
          RENOVATE_AUTODISCOVER: "false"
          LOG_LEVEL: "debug"
          RENOVATE_REPOSITORIES: ${{ github.repository }}